apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  #labels é para qualquer chave valor que eu inventar, não precisa se chamar app
  labels:
    app: segundo-pod
spec:
  containers:
    - name: container-pod-2
      image: nginx:latest
      ports:
        - containerPort: 80