apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
      #Aqui a porta tem que ser defininida dentro do intervalor de 30000-32767
      nodePort: 30000
  selector:
    app: primeiro-pod