apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod
  ports:
    #Aqui o nosso serviço recebe requisições na porta 80 e direciona para a porta 80
    - port: 80